name: Labeling test
on:
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Mark mergeable
        run: gh pr edit "https://github.com/shoma2da/label-test/pull/1" --add-label "mergeable"
